
version: "3"

services:
  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db/mongo-volume:/data/db
