
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src
      - ./tests:/usr/app/tests
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-volume:/data/db
