name: Docker-Compose Action Workflow

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose up -d
        
      - name: check proces
        run: docker-compose ps

      - name: Run test
        run: docker-compose exec app pytest
